version: "3.9"

services:
  nginx:
    image: nginx
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - static:/static
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: cde0701/djangoproject_web
    build: ./app
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn djangoProject.wsgi:application -b 0:80"
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
    env_file:
      - ./.env.dev
volumes:
  postgres_data: